# Generated by Django 4.2.7 on 2026-05-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emocion',
            options={'managed': False, 'verbose_name': 'Emoción', 'verbose_name_plural': 'Emociones'},
        ),
        migrations.AlterModelOptions(
            name='evaluacioninicial',
            options={'managed': False, 'verbose_name': 'Evaluación inicial', 'verbose_name_plural': 'Evaluaciones iniciales'},
        ),
        migrations.AlterModelOptions(
            name='presentacionrecurso',
            options={'managed': False, 'verbose_name': 'Presentación de recurso', 'verbose_name_plural': 'Presentaciones de recurso'},
        ),
        migrations.AlterModelOptions(
            name='recursoapoyo',
            options={'managed': False, 'verbose_name': 'Recurso de apoyo', 'verbose_name_plural': 'Recursos de apoyo'},
        ),
        migrations.AlterModelOptions(
            name='registroemocional',
            options={'managed': False, 'verbose_name': 'Registro emocional', 'verbose_name_plural': 'Registros emocionales'},
        ),
        migrations.AlterModelOptions(
            name='tiporecurso',
            options={'managed': False, 'verbose_name': 'Tipo de recurso', 'verbose_name_plural': 'Tipos de recurso'},
        ),
    ]
